SYS-808 - Get target directory for derivative
UCLALibrary/dlcs-staff-ui pull request #27
Opened 2022-05-18 04:55 UTC by darrowcoucla

Connected to [SYS-808](https://jira.library.ucla.edu/browse/SYS-808)

NOTE: admin.py is unchanged. It is included because spacing was automatically changed by VSCode.

After a file is processed, the submitted file is copied to a destination location (the masters directory), and the derivative file (submaster) is copied to a different location. Create a function that, when supplied with mime_type and item_ark, returns the location for the derivative.

These destination locations are located in the PROJECTS table.
-----
**Acceptance criteria:**

- [x] Get data to construct derivative target from database

-----
**Typical Screenshots**

![image](https://user-images.githubusercontent.com/2350153/168959729-fb0240e0-be3f-4fbc-9a74-7c38419bb63d.png)

-----
**Changed Files**
```
oral_history/
    admin.py
    management/
        commands/
            process_file.py
```

2022-05-18 21:17 UTC, akohler requested changes
@darrowcoucla A few simple changes, mostly to use the more Django-ish way of getting the needed data from the database.
Thanks --Andy

2022-05-18 21:17 UTC, akohler commented on oral_history/management/commands/process_file.py
> +        pfk_value = ProjectItems.objects.filter(
@darrowcoucla There's a more Django-ish way of doing this.  The `QuerySet` returned by `filter()` has convenience methods like `first()`, which returns the "first" row in the set, or `None` if the set is empty.  `first()` returns an object, a `ProjectItems` in this case, and since any given `ProjectItems` will have only one `projectid_fk`, we can use this which is semantically-clearer:

```
>>> pfk_value = ProjectItems.objects.filter(item_ark=item_ark).first().projectid_fk_id
>>> pfk_value
80
```

To explore further:
```
$ docker-compose exec django python manage.py shell
>>> from oral_history.models import Projects, ProjectItems
>>> item_ark = '21198/zz002dx6wh'
>>> pfk_value = ProjectItems.objects.filter(item_ark=item_ark).first().projectid_fk_id
>>> pfk_value
80
```

Getting `submasters_dir` is a little different, since we need one of several possible attributes of `Projects` based on the `submasters_dir_to_find` variable.  Since each `ProjectItem` will have only one foreign key linking it to a `Project`, we don't need the general filter, just `get()`.  We can then use `getattr(model, value)` to get what's needed.  In the same environment as above:

```
>>> submasters_dir_to_find = 'image_submasters_dir'
>>> submasters_dir = getattr(Projects.objects.get(pk=pfk_value), submasters_dir_to_find)
>>> submasters_dir
''
```

It's an empty string because our only `Projects` record has empty values for the different submasters directories.  But to prove it works:
```
>>> submasters_dir_to_find = 'image_masters_dir'
>>> submasters_dir = getattr(Projects.objects.get(pk=pfk_value), submasters_dir_to_find)
>>> submasters_dir
'\\\\ad\\Dlib\\Masters\\dlmasters\\oralhistory\\masters\\'
```

2022-05-18 21:17 UTC, akohler commented on oral_history/management/commands/process_file.py
> +        print("\nsubmaster dir for " + mime_type +
@darrowcoucla As you noted, please remove or replace this with logging.

2022-05-18 23:54 UTC, darrowcoucla commented on oral_history/management/commands/process_file.py
> +    try:
Rewrite noted and expected.

2022-05-18 23:55 UTC, darrowcoucla commented on oral_history/management/commands/process_file.py
> +        print("\nsubmaster dir for " + mime_type +
Debug print replaced with logging.

2022-05-19 00:03 UTC, akohler approved these changes

2022-05-19 00:04 UTC, merged