Sys 800/img process script
UCLALibrary/dlcs-staff-ui pull request #29
Opened 2022-05-24 20:25 UTC by kjallen

This feature fell a bit behind and I merged some of Darrow and Stephen's changes in main back in to catch up.

A ContentFile object is returned after generated a static thumbnail size (to be updated with actual project specific parameters)

2022-05-24 22:50 UTC, akohler requested changes
@kjallen Several fairly minor comments/changes requested.  Once fixed, I'll merge and pick up SYS-838, to save the returned image metadata to the database.  Thanks.

2022-05-24 22:50 UTC, akohler commented on oral_history/scripts/image_processor.py
> +    SUBMASTER_CATEGORY = "Submaster"
I assume we need new ticket(s) for these not-yet-used categories (submaster and master)?

2022-05-24 22:50 UTC, akohler commented on oral_history/scripts/image_processor.py
> +        logger.info("Processing image file ...")
This should include the `src_file_name` to make the logs more useful.

2022-05-24 22:50 UTC, akohler commented on oral_history/scripts/image_processor.py
> +        # error detection goes here
I think these example error comments should come out now.

2022-05-24 22:50 UTC, akohler commented on oral_history/management/commands/process_file.py
>      dest_file_name = dest_dir + 'tmp.jpg'
Noting that `dest_dir` currently is `''` as `calculate_destination_dir()` checks only for sub-masters, and the image submasters dir value is empty on our only `Projects` record.  So `dest_file_name` is always in the current path, which is the top-level Django project directory.  

No change needed here, but is this bad data for the `Projects` record, or incorrect code in `calculate_destination_dir()` which will need a new ticket to specify and fix?

2022-05-24 22:50 UTC, akohler commented on oral_history/management/commands/process_file.py
> +        return img_metadata
`process_media_file()` currently does not capture the return value from `process_tiff()` (or any of the future `process_x()` methods.  Since `img_metadata` is a `ContentFiles` object, I assume this is where that would get saved?

2022-05-24 22:50 UTC, akohler commented on oral_history/scripts/image_processor.py
> +                return(img_metadata)
Stylistic: no parentheses, to match line 43 and other `return` statements.

2022-05-24 22:51 UTC, akohler commented on oral_history/management/commands/process_file.py
> +        return img_metadata
Oops...  Resolving this myself, as I forgot about SYS-838 which will do the actual saving of the `ContentFiles` object.

2022-05-24 23:53 UTC, kjallen commented on oral_history/scripts/image_processor.py
> +    SUBMASTER_CATEGORY = "Submaster"
Correct, I will create tickets for the new categories

2022-05-24 23:53 UTC, kjallen commented on oral_history/management/commands/process_file.py
>      dest_file_name = dest_dir + 'tmp.jpg'
Yes, this is bad data -- will add ticket for updating and proving error handling

2022-05-25 00:07 UTC, akohler approved these changes

2022-05-25 00:08 UTC, merged