Sys 841 create administrative metadata model objects
UCLALibrary/dlcs-staff-ui pull request #30
Opened 2022-05-25 21:18 UTC by darrowcoucla

Connected to [SYS-841](https://jira.library.ucla.edu/browse/SYS-841)

NOTE: some un-modified lines of code were changed by VSCode. Also, migrating created a migration file.

Tables should be added to the OH application model.

-----
**Acceptance criteria:**

Tables are added to the OH application model.
- [x] link_admin_groups
- [x] admin_groups
- [x] admin_types
- [x] admin_values
- [x] admin_terms
- [x] admin_qualifiers
- [x] admin_control_values

-----
**Changed Files**
```
oral_history/
    migrations/
        0004_admincontrolvalues_admingroups_adminqualifiers_and_more.py
    models.py
```

2022-05-25 22:12 UTC, akohler reviewed
@darrowcoucla Other than the `DO_NOTHING` vs. `CASCADE` question, which @kjallen should weigh in on, no changes needed from my POV.

2022-05-25 22:12 UTC, akohler commented on oral_history/models.py
> +        'AdminGroups', models.DO_NOTHING, db_column='admin_groupid_fk', blank=True, null=True)
I believe this (and other) `DO_NOTHING` foreign key behavior should be `CASCADE`.  That's what we've used elsewhere in this project's models, and in the LBS and TERRA projects.

@kjallen Do you have any concerns?  I can be argued into either approach, but we probably should be consistent.  We also will need to test, either way.

Documentation: https://docs.djangoproject.com/en/4.0/ref/models/fields/#arguments

2022-05-26 00:44 UTC, akohler requested changes

2022-05-26 00:44 UTC, akohler commented on oral_history/models.py
> +    admin_groupid_pk = models.IntegerField(primary_key=True)
@darrowcoucla Just discovered a change which probably *will* need to be made: the primary keys need to be changed to `AutoField`, with `auto_created=True`.  Otherwise, these are `NULL`, and Oracle will throw an error because it can't insert a row with a `NULL` primary key.

I just found this with the `ContentFiles` model I created last week: I can't save objects for this very reason.  Making this change fixes that problem (and exposes more, but 1 at a time):
```
-    fileid_pk = models.IntegerField(primary_key=True)
+    fileid_pk = models.AutoField(primary_key=True, auto_created=True)
```
I see @kjallen did this with the models he originally created, like `ProjectItems`.  We need to do the same.

2022-05-26 20:02 UTC, kjallen commented on oral_history/models.py
> +        'AdminGroups', models.DO_NOTHING, db_column='admin_groupid_fk', blank=True, null=True)
Yes, I would vote for `CASCADE`, this is what we used for initial import of DB tables as @akohler mentions. `DO_NOTHING` can be troublesome cleaning up orphaned records, among other things

2022-05-26 20:04 UTC, kjallen commented on oral_history/models.py
> +    admin_groupid_pk = models.IntegerField(primary_key=True)
Confirming @akohler notes, the `auto_created=True` is a deal breaker given our current choice of database

2022-05-26 21:33 UTC, closed without merging

2022-05-26 21:33 UTC, darrowcoucla commented
This PR was replaced with  [PR-33](https://github.com/UCLALibrary/dlcs-staff-ui/pull/33)