Sys 801/create audio processing script
UCLALibrary/dlcs-staff-ui pull request #40
Opened 2022-06-02 20:24 UTC by kjallen

This pr adds first pass at synchronous processing for mp3 generation.

A sample valid and corrupt wav have been added to the `samples/example_project` directory.

The file naming and file sequence will be corrected in SYS-857, and currently use a tmp.mp3 placeholder name

2022-06-02 21:39 UTC, akohler requested changes
@kjallen Without the `audio_processor` script there's not much to review.  The general approach is the same as with images, so should work, but this can't move forward without the audio processing script.

2022-06-02 21:39 UTC, akohler commented on oral_history/management/commands/process_file.py
> +from oral_history.scripts.audio_processor import AudioProcessor
@kjallen `oral_history/scripts/audio_processor.py` is missing from this PR.  That breaks all processing, since `process_file.py` throws `No module named 'oral_history.scripts.audio_processor' ` .  The error is caught, but this is a loss of functionality.

Please add the `audio_processor` script.

2022-06-03 00:33 UTC, akohler requested changes
@kjallen Several fairly minor changes please.

2022-06-03 00:33 UTC, akohler commented on oral_history/management/commands/process_file.py
> +    logger.info(f'{dest_file_name = }')
@kjallen Please move this to line 102; otherwise it does not log when an exception occurs.

2022-06-03 00:33 UTC, akohler commented on oral_history/scripts/audio_processor.py
> +        img_metadata.mime_types = mime_type
`mime_types` should be `mime_type`, per the `ContentFiles` model.

2022-06-03 00:33 UTC, akohler commented on oral_history/scripts/audio_processor.py
> +        img_metadata = ContentFiles()
`img_metadata` does not make sense here - maybe `audio_metadata`?

2022-06-03 00:33 UTC, akohler commented on oral_history/scripts/audio_processor.py
> +            stream = ffmpeg.output(stream, dest_file_name, acodec='libmp3lame', audio_bitrate='320k', ar=44100, ac=2)
Is this worth a comment on the ffmpeg flags used?  The codec and bitrate are clear enough; `ar` (rate in KHz?) and `ac` (audio channels, Google says) are not.

2022-06-03 00:33 UTC, akohler commented on oral_history/management/commands/process_file.py
> +    dest_file_name = dest_dir + 'tmp.mp3'
When I ran this via UI, selecting the valid `sample.wav`, it succeeded, but created `'\\ad\Dlib\dlcontent-prod\oralhistory\tmp.mp3'` in the main application directoy - via the project's audio submasters dir, `\\ad\Dlib\dlcontent-prod\oralhistory\`

OK, but unexpected; maybe `dest_dir` should be mocked within `process_wav` until the problems with `calculate_destination_dir()` are fixed?

2022-06-03 17:39 UTC, kjallen commented on oral_history/scripts/audio_processor.py
> +        img_metadata = ContentFiles()
Yes, poor cut + paste. Updating to `content_metadata` for future extraction into utility class

2022-06-03 17:51 UTC, kjallen commented on oral_history/scripts/audio_processor.py
> +            stream = ffmpeg.output(stream, dest_file_name, acodec='libmp3lame', audio_bitrate='320k', ar=44100, ac=2)
Yes, added. In future, can be considered to pull these out into config file or populated from other source. Currently matching what DLCS has had hard coded, so changes should be extremely infrequent at most

2022-06-03 18:01 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +    dest_file_name = dest_dir + 'tmp.mp3'
Noted. I'll revert this back to local `/tmp/` - The seed data probably should be updated something that resolves to our mock wowza directory. I can add this to ticket SYS-857, which is related (file naming)

2022-06-03 18:07 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +    logger.info(f'{dest_file_name = }')
Removed unreachable code

2022-06-03 21:04 UTC, akohler approved these changes
@kjallen I made a minor code tweak to enable `ContentFiles` saving for audio, and added a `TODO` comment for ffmpeg throwing an error when the output file already exists.  This allowed me to do a complete end-to-end test via the GUI.

Merging --Andy

2022-06-03 21:04 UTC, akohler commented on oral_history/management/commands/process_file.py
> +            derivative_data = process_wav(file_name, item_ark, dest_dir)
I added this to capture `derivative_data` from `process_wav()`, as a quick hack to prevent error with call to `update_db()` at line 63.  This is for this mime_type only; pdf/text will need similar handling.

2022-06-03 21:05 UTC, merged