Sys 857/calculate file name
UCLALibrary/dlcs-staff-ui pull request #44
Opened 2022-06-09 05:48 UTC by kjallen

Functions have been added to calculate the appropriate file name given an item ark, file use (master, submaster...) and extension (mp3, wav).

To test, in python console run the following given the existing test data in the python interpreter on the django container:

```
from django.db.models import Max
from oral_history.models import ContentFiles
exec(open("oral_history/management/commands/process_file.py").read())

get_new_content_file_name("21198/zz002dx6rf", "submaster", "mp3")
'21198-zz002dx6rf-1-submaster.mp3'

cf = ContentFiles.objects.get(fileid_pk=1)
cf.file_sequence = "1"
cf.save()

get_new_content_file_name("21198/zz002dx6rf", "submaster", "mp3")
'21198-zz002dx6rf-2-submaster.mp3'
```

This calculates the appropriate file name given the existing sequence in the `ContentFiles` table, increments that value by 1, and repeats the operation, generating the next sequence given the updated value in the database.

In addition to this change, the `calculate_destination_dir()` has been reverted to always return `/tmp/` as the root directory until an environment variable solution is implemented

2022-06-09 18:25 UTC, akohler requested changes
@kjallen This does work as expected, and thanks for the testing scenario.  FYI, we can just import `process_file` - I did this:
```
import oral_history.management.commands.process_file as pf
pf.whatever_command...
```
The main change/question is with `get_content_files()`, the use of `get()` vs `filter()`; I think `filter()` matches the intent, and would allow (re)use of `get_content_files()`.

Thanks --Andy

2022-06-09 18:25 UTC, akohler commented on oral_history/management/commands/process_file.py
> +def get_content_files(divid):
`get_content_files()` is currently unused.

2022-06-09 18:25 UTC, akohler commented on oral_history/management/commands/process_file.py
> +        seq_string = ContentFiles.objects.filter(divid_fk=divid).aggregate(seq=Max('file_sequence'))['seq']
If `get_content_files()` is changed to return a queryset via `filter`, the result of that could be used here:
```
cf = get_content_files(divid)
seq_string = cf.aggregate(seq=Max('file_sequence'))['seq']
...
```

2022-06-09 18:25 UTC, akohler commented on oral_history/management/commands/process_file.py
> +    project_item = get_project_item(item_ark)
`get_project_item()` can return `None`, so the next line fails:
```
>>> x=pf.get_project_item('abc')
>>> x
>>> type(x)
<class 'NoneType'>
>>> x.divid_pk
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'divid_pk'
```

Does this need catching here, or is the current catching of it in `process_tiff()` etc. enough?

2022-06-09 18:25 UTC, akohler commented on oral_history/management/commands/process_file.py
> +    item_ark = item_ark.replace("/", "-").lower()
Simpler to apply `.lower()` to `content_file_name`, instead of these 3 separate uses.

2022-06-09 18:25 UTC, akohler commented on oral_history/management/commands/process_file.py
> +    content_file_name = (item_ark
Please use f-strings instead of concatenation.

2022-06-09 20:33 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +        return ContentFiles.objects.get(divid_fk=divid)
Updated to use filter and return empty QuerySet if no match

2022-06-09 20:34 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +def get_content_files(divid):
Updated get_content_files to get_content_files_by_project_item for clarity and incorporated use

2022-06-10 00:14 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +        seq_string = ContentFiles.objects.filter(divid_fk=divid).aggregate(seq=Max('file_sequence'))['seq']
Updated to return QuerySet

2022-06-10 00:15 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +    content_file_name = (item_ark
Updated to use f-strings

2022-06-10 00:15 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +    item_ark = item_ark.replace("/", "-").lower()
Removed individual field `.lower()` invocations

2022-06-10 00:22 UTC, kjallen commented on oral_history/management/commands/process_file.py
> +    project_item = get_project_item(item_ark)
Updated to return `None` if no match found for a submitted item ark

2022-06-10 00:49 UTC, akohler approved these changes
@kjallen Thanks for making the changes.  Reviewed and tested, merging.

2022-06-10 00:50 UTC, merged